# Generated by Django 4.2.5 on 2023-09-23 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_quizquestion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizcategory',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='quizquestion',
            options={'verbose_name_plural': 'Questions'},
        ),
        migrations.RemoveField(
            model_name='quizcategory',
            name='image',
        ),
    ]
