# Generated by Django 4.2.5 on 2023-09-23 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_quizcategory_rename_q_level_quizlevel_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestion',
            name='category',
        ),
        migrations.DeleteModel(
            name='QuizCategory',
        ),
    ]
