# Generated by Django 4.2.5 on 2023-09-23 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_alter_quizquestion_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level_set', to='exam.quizlevel'),
        ),
    ]
